export const Luzon = [
    //LUZON
    // Ifugao
    { city: "Aguinaldo", zipCode: 3606 },
    { city: "Asipulo", zipCode: 3610 },
    { city: "Banaue", zipCode: 3601 },
    { city: "Hingyon", zipCode: 3607 },
    { city: "Hungduan", zipCode: 3603 },
    { city: "Kiangan", zipCode: 3604 },
    { city: "Lagawe", zipCode: 3600 },
    { city: "Lamut", zipCode: 3605 },
    { city: "Mayaoyao / Mayoyao", zipCode: 3602 },
    { city: "Potia", zipCode: 3608 },
    { city: "Tinoc", zipCode: 3609 },
    // Ilocos Norte
    { city: "Adams", zipCode: 2922 },
    { city: "Bacarra", zipCode: 2916 },
    { city: "Badoc", zipCode: 2904 },
    { city: "Bangui", zipCode: 2920 },
    { city: "Batac", zipCode: 2906 },
    { city: "Burgos", zipCode: 2918 },
    { city: "Carasi", zipCode: 2911 },
    { city: "Currimao", zipCode: 2903 },
    { city: "Dingras", zipCode: 2913 },
    { city: "Dumalneg", zipCode: 2921 },
    { city: "Laoag City", zipCode: 2900 },
    { city: "Marcos", zipCode: 2907 },
    { city: "Nueva Era", zipCode: 2909 },
    { city: "Pagudpud", zipCode: 2919 },
    { city: "Paoay", zipCode: 2902 },
    { city: "Pasuquin", zipCode: 2917 },
    { city: "Piddig", zipCode: 2912 },
    { city: "Pinili", zipCode: 2905 },
    { city: "San Nicolas", zipCode: 2901 },
    { city: "Sarrat", zipCode: 2914 },
    { city: "Solsona", zipCode: 2910 },
    { city: "Vintar", zipCode: 2915 },
    // Ilocos Sur
    { city: "Alilem", zipCode: 2716 },
    { city: "Binayoyo", zipCode: 2708 },
    { city: "Bantay", zipCode: 2727 },
    { city: "Burgos", zipCode: 2724 },
    { city: "Cabugao", zipCode: 2732 },
    { city: "Candon", zipCode: 2710 },
    { city: "Caoayan", zipCode: 2702 },
    { city: "Cervantes", zipCode: 2718 },
    { city: "Galimuyod", zipCode: 2709 },
    { city: "Gregorio Del Pilar", zipCode: 2720 },
    { city: "Lidilda", zipCode: 2723 },
    { city: "Magsingal", zipCode: 2730 },
    { city: "Nagbukel", zipCode: 2725 },
    { city: "Narvacan", zipCode: 2704 },
    { city: "Quirino", zipCode: 2721 },
    { city: "Salsedo", zipCode: 2711 },
    { city: "San Emilio", zipCode: 2722 },
    { city: "San Esteban", zipCode: 2706 },
    { city: "San Ildefonso", zipCode: 2728 },
    { city: "San Juan", zipCode: 2731 },
    { city: "San Vicente", zipCode: 2726 },
    { city: "Santa", zipCode: 2703 },
    { city: "Santa Catalina", zipCode: 2701 },
    { city: "Santa Cruz", zipCode: 2713 },
    { city: "Santa Lucia", zipCode: 2712 },
    { city: "Santa Maria", zipCode: 2705 },
    { city: "Santiago", zipCode: 2707 },
    { city: "Santo Domingo", zipCode: 2729 },
    { city: "Sicay", zipCode: 2719 },
    { city: "Sinait", zipCode: 2733 },
    { city: "Sugpon", zipCode: 2717 },
    { city: "Suyo", zipCode: 2715 },
    { city: "Tagudin", zipCode: 2714 },
    { city: "Vigan", zipCode: 2700 },
    // Isabela
    { city: "Alicia", zipCode: 3306 },
    { city: "Angadanan", zipCode: 3307 },
    { city: "Aurora", zipCode: 3316 },
    { city: "Benito Soliven", zipCode: 3331 },
    { city: "Burgos", zipCode: 3322 },
    { city: "Cabagan", zipCode: 3328 },
    { city: "Cabatuan", zipCode: 3315 },
    { city: "Cauayan", zipCode: 3305 },
    { city: "Cordon", zipCode: 3312 },
    { city: "Delfin Albano", zipCode: 3326 },
    { city: "Dinapigui", zipCode: 3335 },
    { city: "Divilacan", zipCode: 3336 },
    { city: "Echague", zipCode: 3309 },
    { city: "Gamu", zipCode: 3301 },
    { city: "Ilagan City", zipCode: 3300 },
    { city: "Jones", zipCode: 3313 },
    { city: "Luna", zipCode: 3304 },
    { city: "Maconacon", zipCode: 3333 },
    { city: "Mallig", zipCode: 3323 },
    { city: "Naguilian", zipCode: 3302 },
    { city: "Palanan", zipCode: 3334 },
    { city: "Quezon", zipCode: 3324 },
    { city: "Quirino", zipCode: 3321 },
    { city: "Ramon", zipCode: 3319 },
    { city: "Reina Mercedes", zipCode: 3303 },
    { city: "Roxas", zipCode: 3320 },
    { city: "San Agustin", zipCode: 3314 },
    { city: "San Guillermo", zipCode: 3308 },
    { city: "San Isidro", zipCode: 3310 },
    { city: "San Maguel (Callang)", zipCode: 3317 },
    { city: "San Mariano", zipCode: 3332 },
    { city: "San Mateo", zipCode: 3318 },
    { city: "San Pablo", zipCode: 3329 },
    { city: "Santa Maria", zipCode: 3330 },
    { city: "Santiago", zipCode: 3311 },
    { city: "Santo Tomas", zipCode: 3327 },
    { city: "Tumauini", zipCode: 3325 },
    // Kalinga
	{ city: "Balbalan", zipCode: 3801 },
    { city: "Calanasan", zipCode: 3814 },
    { city: "Conner", zipCode: 3807 },
    { city: "Flora", zipCode: 3807 },
    { city: "Kabugao", zipCode: 3809 },
    { city: "Liwan (Rizal)", zipCode: 3808 },
    { city: "Lubuagan", zipCode: 3802 },
    { city: "Luna", zipCode: 3813 },
    { city: "Pasil", zipCode: 3803 },
    { city: "Pinukpuk", zipCode: 3806 },
    { city: "Pudtol", zipCode: 3812 },
    { city: "Santa Marcela", zipCode: 3811 },
    { city: "Tabuk", zipCode: 3800 },
    { city: "Tanudan", zipCode: 3805 },
    { city: "Tinglayan", zipCode: 3804 },
    // Laguna
    { city: "Alaminos", zipCode: 4001 },
    { city: "Bay", zipCode: 4033 },
    { city: "Biñan", zipCode: 4024 },
    { city: "Cabuyao", zipCode: 4025 },
    { city: "Calamba", zipCode: 4027 },
    { city: "Calauan", zipCode: 4012 },
    { city: "Cavinti", zipCode: 4013 },
    { city: "Famy", zipCode: 4021 },
    { city: "Kalayaan", zipCode: 4015 },
    { city: "Liliw", zipCode: 4004 },
    { city: "Los Baños", zipCode: 4030 },
    { city: "Luisiana", zipCode: 4032 },
    { city: "Lumban", zipCode: 4014 },
    { city: "Mabitac", zipCode: 4020 },
    { city: "Magdalena", zipCode: 4007 },
    { city: "Majayjay", zipCode: 4005 },
    { city: "Nagcarlan", zipCode: 4002 },
    { city: "Paete", zipCode: 4016 },
    { city: "Pagsanjan", zipCode: 4008 },
    { city: "Pakil", zipCode: 4017 },
    { city: "Pangil", zipCode: 4018 },
    { city: "Pila", zipCode: 4010 },
    { city: "Rizal", zipCode: 4003 },
    { city: "San Pablo", zipCode: 4000 },
    { city: "San Pedro", zipCode: 4023 },
    { city: "Santa Cruz", zipCode: 4009 },
    { city: "Santa Maria", zipCode: 4022 },
    { city: "Santa Rosa", zipCode: 4026 },
    { city: "Siniloan", zipCode: 4019 },
    { city: "Victoria", zipCode: 4011 },
    //La Union
    { city: "Agoo", zipCode: 2504 },
    { city: "Aringay", zipCode: 2503 },
    { city: "Bacnotan", zipCode: 2515 },
    { city: "Bagulin", zipCode: 2512 },
    { city: "Balaoan", zipCode: 2517 },
    { city: "Bangar", zipCode: 2519 },
    { city: "Bauang", zipCode: 2501 },
    { city: "Burgos", zipCode: 2510 },
    { city: "Caba", zipCode: 2502 },
    { city: "Damortis", zipCode: 2507 },
    { city: "Luna", zipCode: 2518 },
    { city: "Naguilan", zipCode: 2511 },
    { city: "Pugo", zipCode: 2508 },
    { city: "Rosario", zipCode: 2506 },
    { city: "San Fernando", zipCode: 2500 },
    { city: "San Gabriel", zipCode: 2513 },
    { city: "San Juan", zipCode: 2514 },
    { city: "Santo Tomas", zipCode: 2505 },
    { city: "Santol", zipCode: 2516 },
    { city: "Sudepen", zipCode: 2520 },
    { city: "Tubao", zipCode: 2509 },
    //Marinduque
    { city: "Boac", zipCode: 4900 },
    { city: "Buenavista", zipCode: 4904 },
    { city: "Gasan", zipCode: 4905 },
    { city: "Mogpog", zipCode: 4901 },
    { city: "Santa Cruz", zipCode: 4902 },
    { city: "Torrijos", zipCode: 4903 },
    //Mindoro Occidental 
    { city: "Abra de Ilog", zipCode: 5108 },
    { city: "Calintaan", zipCode: 5102 },
    { city: "Looc", zipCode: 5111 },
    { city: "Lubang", zipCode: 5109 },
    { city: "Magsaysay", zipCode: 5101 },
    { city: "Mamburao", zipCode: 5106 },
    { city: "Paluan", zipCode: 5107 },
    { city: "Rizal", zipCode: 5103 },
    { city: "Sablayan", zipCode: 5104 },
    { city: "San Jose", zipCode: 5100 },
    { city: "Santa Cruz", zipCode: 5105 },
    { city: "Tilik", zipCode: 5110 },
    //Mindoro Oriental  
    { city: "Baco", zipCode: 5201 },
    { city: "Bansud", zipCode: 5210 },
    { city: "Bongabon", zipCode: 5211 },
    { city: "Bulalacao", zipCode: 5214 },
    { city: "Calapan", zipCode: 5200 },
    { city: "Gloria", zipCode: 5209 },
    { city: "Mansalay", zipCode: 5208 },
    { city: "Pola", zipCode: 5206 },
    { city: "Puerto Galera", zipCode: 5203 },
    { city: "Roxas", zipCode: 5212 },
    { city: "San Teodoro", zipCode: 5202 },
    { city: "Socorro", zipCode: 5207 },
    { city: "Victoria", zipCode: 5205 },
    //Mountain Province
	{ city: "Barlig", zipCode: 2623 },
    { city: "Bauko", zipCode: 2621 },
    { city: "Besao", zipCode: 2618 },
    { city: "Bontoc", zipCode: 2616 },
    { city: "Natonin", zipCode: 2624 },
    { city: "Paracelis", zipCode: 2625 },
    { city: "Sabangan", zipCode: 2622 },
    { city: "Sadanga", zipCode: 2617 },
    { city: "Sagada", zipCode: 2619 },
    { city: "Tadian", zipCode: 2620 },
    //Nueva Ecija
	{ city: "Aliaga", zipCode: 3111 },
    { city: "Bongabon", zipCode: 3128 },
    { city: "Cabanatuan City", zipCode: 3100 },
    { city: "Cabiao", zipCode: 3107 },
    { city: "Carranglan", zipCode: 3123 },
    { city: "Central Luzon State University (CLSU)", zipCode: 3120 },
    { city: "Cuyapao", zipCode: 3117 },
    { city: "Fort Magsaysay", zipCode: 3130 },
    { city: "Gabaldon", zipCode: 3131 },
    { city: "Gapan", zipCode: 3105 },
    { city: "Gen. M. Natividad", zipCode: 3125 },
    { city: "Gen. Tinio", zipCode: 3104 },
    { city: "Guimba", zipCode: 3115 },
    { city: "Jaen", zipCode: 3109 },
    { city: "Laur", zipCode: 3129 },
    { city: "Lucab", zipCode: 3112 },
    { city: "Llanera", zipCode: 3126 },
    { city: "Lupao", zipCode: 3122 },
    { city: "Munoz", zipCode: 3119 },
    { city: "Nampicuan", zipCode: 3116 },
    { city: "Palayan City", zipCode: 3132 },
    { city: "Pantabangan", zipCode: 3124 },
    { city: "Penaranda", zipCode: 3103 },
    { city: "Quezon", zipCode: 3113 },
    { city: "Rizal", zipCode: 3127 },
    { city: "San Antonio", zipCode: 3108 },
    { city: "San Isidro", zipCode: 3106 },
    { city: "San Jose City", zipCode: 3121 },
    { city: "San Leonardo", zipCode: 3102 },
    { city: "Santa Rosa", zipCode: 3101 },
    { city: "Santo Domingo", zipCode: 3133 },
    { city: "Talavera", zipCode: 3114 },
    { city: "Talugtog", zipCode: 3118 },
    { city: "Zaragosa", zipCode: 3110 },
    //Nueva Viscaya
	{ city: "Alfonso Castañeda", zipCode: 3714 },
    { city: "Ambaguio", zipCode: 3701 },
    { city: "Aritao", zipCode: 3704 },
    { city: "Bagabag", zipCode: 3711 },
    { city: "Bambang", zipCode: 3702 },
    { city: "Bayombong", zipCode: 3700 },
    { city: "Diadi", zipCode: 3712 },
    { city: "Dupax del Norte", zipCode: 3706 },
    { city: "Dupax del Sur", zipCode: 3707 },
    { city: "Kasibu", zipCode: 3703 },
    { city: "Kayapa", zipCode: 3708 },
    { city: "Quezon", zipCode: 3713 },
    { city: "Solano", zipCode: 3709 },
    { city: "Sta. Fe (Imugan)", zipCode: 3705 },
    { city: "Villa Verde (Ibung)", zipCode: 3710 },
    //Palawan
    { city: "Aborlan", zipCode: 5302 },
    { city: "Agutaya", zipCode: 5320 },
    { city: "Araceli", zipCode: 5311 },
    { city: "Balabac", zipCode: 5307 },
    { city: "Bataraza", zipCode: 5306 },
    { city: "Brooke's Point", zipCode: 5305 },
    { city: "Busuanga", zipCode: 5317 },
    { city: "Cagayancillo", zipCode: 5321 },
    { city: "Coron", zipCode: 5316 },
    { city: "Culion", zipCode: 5315 },
    { city: "Cuyo", zipCode: 5318 },
    { city: "Dumaran", zipCode: 5310 },
    { city: "El Nido (Baquit)", zipCode: 5313 },
    { city: "Iwahig Penal Colony", zipCode: 5301 },
    { city: "Kalayaan", zipCode: 5322 },
    { city: "Linapacan", zipCode: 5314 },
    { city: "Magsaysay", zipCode: 5319 },
    { city: "Narra (Panacan)", zipCode: 5303 },
    { city: "Puerto Princesa City", zipCode: 5300 },
    { city: "Quezon", zipCode: 5304 },
    { city: "Roxas", zipCode: 5308 },
    { city: "San Vicente", zipCode: 5309 },
    { city: "Taytay", zipCode: 5312 },
    //Pampanga
    { city: "Angeles City", zipCode: 2009 },
    { city: "Apalit", zipCode: 2016 },
    { city: "Arayat", zipCode: 2012 },
    { city: "Bacolor", zipCode: 2001 },
    { city: "Basa Air Base", zipCode: 2007 },
    { city: "Candaba", zipCode: 2013 },
    { city: "Floridablanca", zipCode: 2006 },
    { city: "Guagua", zipCode: 2003 },
    { city: "Lubao", zipCode: 2005 },
    { city: "Mabalacat", zipCode: 2010 },
    { city: "Macabebe", zipCode: 2018 },
    { city: "Magalang", zipCode: 2011 },
    { city: "Masantol", zipCode: 2017 },
    { city: "Mexico", zipCode: 2021 },
    { city: "Minalin", zipCode: 2019 },
    { city: "Porac", zipCode: 2008 },
    { city: "San Fernando", zipCode: 2000 },
    { city: "San Luis", zipCode: 2014 },
    { city: "San Simon", zipCode: 2015 },
    { city: "Santa Ana", zipCode: 2022 },
    { city: "Santa Rita", zipCode: 2002 },
    { city: "Santo Tomas", zipCode: 2020 },
    { city: "Sasmuan (old: Sexmoan)", zipCode: 2004 },
    //Pangasinan
    { city: "Agno", zipCode: 2408 },
    { city: "Aguilar", zipCode: 2415 },
    { city: "Alaminos", zipCode: 2404 },
    { city: "Alcala", zipCode: 2425 },
    { city: "Anda", zipCode: 2405 },
    { city: "Asingan", zipCode: 2439 },
    { city: "Balungao", zipCode: 2442 },
    { city: "Bani", zipCode: 2407 },
    { city: "Basista", zipCode: 2422 },
    { city: "Bautista", zipCode: 2424 },
    { city: "Bayambang", zipCode: 2423 },
    { city: "Binalonan", zipCode: 2436 },
    { city: "Binmaley", zipCode: 2417 },
    { city: "Bolinao", zipCode: 2406 },
    { city: "Bugallon", zipCode: 2416 },
    { city: "Burgos", zipCode: 2410 },
    { city: "Calasiao", zipCode: 2418 },
    { city: "Dagupan City", zipCode: 2400 },
    { city: "Dasol", zipCode: 2411 },
    { city: "Infanta", zipCode: 2412 },
    { city: "Labrador", zipCode: 2402 },
    { city: "Laoac", zipCode: 2437 },
    { city: "Lingayen", zipCode: 2401 },
    { city: "Mabini", zipCode: 2409 },
    { city: "Malasiqui", zipCode: 2421 },
    { city: "Manaoag", zipCode: 2430 },
    { city: "Mangaldan", zipCode: 2432 },
    { city: "Mangatarem", zipCode: 2413 },
    { city: "Mapandan", zipCode: 2429 },
    { city: "Natividad", zipCode: 2446 },
    { city: "Pozorrubio", zipCode: 2435 },
    { city: "Rosales", zipCode: 2441 },
    { city: "San Carlos City", zipCode: 2420 },
    { city: "San Fabian", zipCode: 2433 },
    { city: "San Jacinto", zipCode: 2431 },
    { city: "San Manuel", zipCode: 2438 },
    { city: "San Nicolas", zipCode: 2447 },
    { city: "San Quintin", zipCode: 2444 },
    { city: "Santa Barbara", zipCode: 2419 },
    { city: "Santa Maria", zipCode: 2440 },
    { city: "Santo Tomas", zipCode: 2426 },
    { city: "Sison", zipCode: 2434 },
    { city: "Sual", zipCode: 2403 },
    { city: "Tayug", zipCode: 2445 },
    { city: "Umingan", zipCode: 2443 },
    { city: "Urbiztondo", zipCode: 2414 },
    { city: "Urdaneta", zipCode: 2428 },
    { city: "Villasis", zipCode: 2427 },
    //Quezon Province
    { city: "Agdangan", zipCode: 4304 },
    { city: "Alabat", zipCode: 4333 },
    { city: "Atimonan", zipCode: 4331 },
    { city: "Buenavista", zipCode: 4320 },
    { city: "Burdeos", zipCode: 4340 },
    { city: "Calauag", zipCode: 4318 },
    { city: "Candelaria", zipCode: 4323 },
    { city: "Catanuan", zipCode: 4311 },
    { city: "Dolores", zipCode: 4326 },
    { city: "Gen. Luna", zipCode: 4310 },
    { city: "Gen. Nakar", zipCode: 4338 },
    { city: "Guinayangan", zipCode: 4319 },
    { city: "Gumaca", zipCode: 4306 },
    { city: "Hondagua", zipCode: 4317 },
    { city: "Infanta", zipCode: 4336 },
    { city: "Jomalig", zipCode: 4342 },
    { city: "Lopez", zipCode: 4316 },
    { city: "Lucban", zipCode: 4328 },
    { city: "Lucena City", zipCode: 4301 },
    { city: "Macalelon", zipCode: 4309 },
    { city: "Mauban", zipCode: 4330 },
    { city: "Mulanay", zipCode: 4312 },
    { city: "Padre Burgos", zipCode: 4303 },
    { city: "Pagbilao", zipCode: 4302 },
    { city: "Panukulan", zipCode: 4337 },
    { city: "Patnonangan", zipCode: 4341 },
    { city: "Perez", zipCode: 4334 },
    { city: "Pitogo", zipCode: 4308 },
    { city: "Plaridel", zipCode: 4306 },
    { city: "Polilio", zipCode: 4339 },
    { city: "Quezon", zipCode: 4332 },
    { city: "Quezon Capitol", zipCode: 4300 },
    { city: "Real", zipCode: 4335 },
    { city: "Sampaloc", zipCode: 4329 },
    { city: "San Andres", zipCode: 4314 },
    { city: "San Antonio", zipCode: 4324 },
    { city: "San Francisco", zipCode: 4315 },
    { city: "San Narciso", zipCode: 4313 },
    { city: "Sariaya", zipCode: 4322 },
    { city: "Tagkawayan", zipCode: 4321 },
    { city: "Tayabas", zipCode: 4327 },
    { city: "Tiaong", zipCode: 4325 },
    { city: "Unisan", zipCode: 4305 },
    //Quirino Province
    { city: "Aglipay", zipCode: 3403 },
    { city: "Cabarruguis", zipCode: 3400 },
    { city: "Diffun", zipCode: 3401 },
    { city: "Maddela", zipCode: 3404 },
    { city: "Nagtipunan (Abbag)", zipCode: 3405 },
    { city: "Saguday", zipCode: 3402 },
    //Rizal Province
    { city: "Antipolo", zipCode: 1870 },
    { city: "Montalban (Rodriguez)", zipCode: 1860 },
    { city: "San Mateo", zipCode: 1850 },
    { city: "Teresa", zipCode: 1880 },
    { city: "Angono", zipCode: 1930 },
    { city: "Baras", zipCode: 1970 },
    { city: "Binangonan", zipCode: 1940 },
    { city: "Cainta", zipCode: 1900 },
    { city: "Cardona", zipCode: 1950 },
    { city: "Jala-Jala", zipCode: 1990 },
    { city: "Morong", zipCode: 1960 },
    { city: "Pililia", zipCode: 1910 },
    { city: "Tanay", zipCode: 1980 },
    { city: "Taytay", zipCode: 1920 },
    //Sorsogonl Province
    { city: "Bacon", zipCode: 4701 },
    { city: "Barcelona", zipCode: 4712 },
    { city: "Bulan", zipCode: 4706 },
    { city: "Bulusan", zipCode: 4704 },
    { city: "Casiguran", zipCode: 4702 },
    { city: "Castilla", zipCode: 4713 },
    { city: "Donsol", zipCode: 4715 },
    { city: "Gubat", zipCode: 4710 },
    { city: "Irosin", zipCode: 4707 },
    { city: "Juban", zipCode: 4703 },
    { city: "Magallanes", zipCode: 4705 },
    { city: "Matnog", zipCode: 4708 },
    { city: "Pilar", zipCode: 4714 },
    { city: "Prieto Diaz", zipCode: 4711 },
    { city: "Sta. Magdalena", zipCode: 4709 },
    { city: "Sorsogon", zipCode: 4700 },
    //Tarlac
	 { city: "Anao", zipCode: 2310},
	 { city: "Bamban", zipCode: 2317},
	 { city: "Camiling", zipCode: 2306},
	 { city: "Capas", zipCode: 2315},
	 { city: "Conception", zipCode: 2316},
	 { city: "Gerona", zipCode: 2302},
	 { city: "La Paz", zipCode: 2314},
	 { city: "Mayantoc", zipCode: 2304},
	 { city: "Mancada", zipCode: 2308},
	 { city: "Paniqui", zipCode: 2307},
	 { city: "Pura", zipCode: 2312},
	 { city: "Ramos", zipCode: 2311},
	 { city: "San Clemente", zipCode: 2305},
	 { city: "San Manuel", zipCode: 2309},
	 { city: "San Miguel", zipCode: 2301},
	 { city: "Sta. Ignacia", zipCode: 2303},
	 { city: "Tarlac", zipCode: 2300},
	 { city: "Victoria", zipCode: 2313},
    //Zambales
	{ city: "Botolan", zipCode: 2202},
	{ city: "Cabangan", zipCode: 2203},
	{ city: "Candelaria", zipCode: 2212},
	{ city: "Castillejos", zipCode: 2208},
	{ city: "Iba", zipCode:2201},
	{ city: "Masinloc", zipCode: 2211},
	{ city: "Olongapo City", zipCode: 2200},
	{ city: "Palauig", zipCode: 2210},
	{ city: "San Antonio", zipCode: 2206},
    { city: "San Felipe", zipCode: 2204},
    { city: "San Marcelino", zipCode: 2207},
    { city: "San Narciso", zipCode: 2205},
    { city: "Sta. Cruz", zipCode: 2213},
    { city: "Subic", zipCode: 2209}
]

export const Visayas = [
    //VISAYAS
    //Aklan
	{ city: "Altavas", zipCode: 5616},
	{ city: "Balite", zipCode: 5614},
	{ city: "Banga", zipCode: 5601},
	{ city: "Batan", zipCode: 5615},
	{ city: "Buruanga", zipCode: 5609},
	{ city: "Ibajay", zipCode: 5613},
	{ city: "Kalibo", zipCode: 5600},
	{ city: "Lezo", zipCode: 5605},
	{ city: "Libacao", zipCode: 5602},
	{ city: "Madalag", zipCode: 5603},
	{ city: "Makato", zipCode: 5611},
	{ city: "Malay", zipCode: 5608},
	{ city: "Malinao", zipCode: 5606},
	{ city: "Nabas", zipCode: 5607},
	{ city: "New Washington", zipCode: 5610},
	{ city: "Numancia", zipCode: 5604},
	{ city: "Tangalan", zipCode: 5612},
    //Antique
	{ city: "Anini-y", zipCode: 5717},
	{ city: "Barbasa", zipCode: 5706},
	{ city: "Belison", zipCode: 5701},
	{ city: "Bugasong", zipCode: 5704},
	{ city: "Caluya", zipCode: 5711},
	{ city: "Culasi", zipCode: 5708},
	{ city: "Hamtic", zipCode: 5715},
	{ city: "Lawa-an", zipCode: 5705},
	{ city: "Libertad", zipCode: 5710},
	{ city: "Pandan", zipCode: 5712},
	{ city: "Patnongan", zipCode: 5702},
	{ city: "San Jose", zipCode: 5700},
	{ city: "San Remedio", zipCode: 5714},
	{ city: "Sebaste", zipCode: 5709},
	{ city: "Sibalom", zipCode: 5713},
	{ city: "Tibiao", zipCode: 5707},
	{ city: "Tobias Fornier (Dao)", zipCode: 5716},
	{ city: "Valderama", zipCode: 5703},
    //Biliran
    { city: "Almeria", zipCode: 6544},
    { city: "Biliran", zipCode: 6549},
    { city: "Cabuccayan", zipCode: 6550},
    { city: "Caibiran", zipCode: 6548},
    { city: "Culaba", zipCode: 6547},
    { city: "Kawayan", zipCode: 6545},
    { city: "Maripipi", zipCode: 6546},
    { city: "Naval", zipCode: 6543},
    //Bohol
    { city: "Alburquerque", zipCode: 6302 },
    { city: "Alicia", zipCode: 6314 },
    { city: "Anda", zipCode: 6311 },
    { city: "Antequera", zipCode: 6335 },
    { city: "Baclayon", zipCode: 6301 },
    { city: "Balilihan", zipCode: 6342 },
    { city: "Batuan", zipCode: 6318 },
    { city: "Bien Unido", zipCode: 6326 },
    { city: "Bilar", zipCode: 6317 },
    { city: "Buenavista", zipCode: 6333 },
    { city: "Calape", zipCode: 6328 },
    { city: "Candijay", zipCode: 6312 },
    { city: "Carlos P. Garcia (Dao)", zipCode: 6346 },
    { city: "Carmen", zipCode: 6319 },
    { city: "Catigbian", zipCode: 6343 },
    { city: "Clarin", zipCode: 6330 },
    { city: "Corella", zipCode: 6337 },
    { city: "Cortes", zipCode: 6341 },
    { city: "Dagohoy", zipCode: 6322 },
    { city: "Danao", zipCode: 6344 },
    { city: "Dauis", zipCode: 6339 },
    { city: "Dimiao", zipCode: 6305 },
    { city: "Duero", zipCode: 6309 },
    { city: "Garcia Hernandez", zipCode: 6307 },
    { city: "Guindulman", zipCode: 6310 },
    { city: "Inabanga", zipCode: 6332 },
    { city: "Jagna", zipCode: 6308 },
    { city: "Jetafe", zipCode: 6334 },
    { city: "Lila", zipCode: 6304 },
    { city: "Loay", zipCode: 6303 },
    { city: "Loboc", zipCode: 6316 },
    { city: "Loon", zipCode: 6327 },
    { city: "Mabini", zipCode: 6313 },
    { city: "Maribojoc", zipCode: 6336 },
    { city: "Panglao", zipCode: 6340 },
    { city: "Pilar", zipCode: 6321 },
    { city: "Sagbayan", zipCode: 6331 },
    { city: "San Isidro", zipCode: 6345 },
    { city: "San Miguel", zipCode: 6323 },
    { city: "Sevilla", zipCode: 6347 },
    { city: "Sierra Bullones", zipCode: 6320 },
    { city: "Sikatuna", zipCode: 6338 },
    { city: "Tagbilaran City", zipCode: 6300 },
    { city: "Talibon", zipCode: 6325 },
    { city: "Trinidad", zipCode: 6324 },
    { city: "Tubigon", zipCode: 6329 },
    { city: "Ubay", zipCode: 6315 },
    { city: "Valencia", zipCode: 6306 },
    //Capiz
    { city: "Cuartero", zipCode: 5811 },
    { city: "Dao", zipCode: 5810 },
    { city: "Dumalag", zipCode: 5813 },
    { city: "Dumarao", zipCode: 5812 },
    { city: "Ivisan", zipCode: 5805 },
    { city: "Jamindan", zipCode: 5808 },
    { city: "Ma-Ayon", zipCode: 5809 },
    { city: "Mambusao", zipCode: 5807 },
    { city: "Panay", zipCode: 5801 },
    { city: "Panitan", zipCode: 5815 },
    { city: "Pilar", zipCode: 5804 },
    { city: "President Roxas", zipCode: 5803 },
    { city: "Pontevedra", zipCode: 5802 },
    { city: "Roxas City", zipCode: 5800 },
    { city: "Sapian", zipCode: 5806 },
    { city: "Sigma", zipCode: 5816 },
    { city: "Tapaz", zipCode: 5814 },
    //Cebu
    { city: "Alcantara", zipCode: 6033 },
    { city: "Alcoy", zipCode: 6023 },
    { city: "Alegria", zipCode: 6030 },
    { city: "Aloguinsan", zipCode: 6040 },
    { city: "Argao", zipCode: 6021 },
    { city: "Asturias", zipCode: 6042 },
    { city: "Badian", zipCode: 6031 },
    { city: "Balamban", zipCode: 6041 },
    { city: "Bantayan", zipCode: 6052 },
    { city: "Barili", zipCode: 6036 },
    { city: "Bogo City", zipCode: 6010 },
    { city: "Boljoon", zipCode: 6024 },
    { city: "Borbon", zipCode: 6008 },
    { city: "Carcar City", zipCode: 6019 },
    { city: "Carmen", zipCode: 6005 },
    { city: "Catmon", zipCode: 6006 },
    { city: "Cebu City", zipCode: 6000 },
    { city: "Compostela", zipCode: 6003 },
    { city: "Consolacion", zipCode: 6001 },
    { city: "Cordova", zipCode: 6017 },
    { city: "Daanbantayan", zipCode: 6013 },
    { city: "Dalaguete", zipCode: 6022 },
    { city: "Danao City", zipCode: 6004 },
    { city: "Dumanjug", zipCode: 6035 },
    { city: "Ginatilan", zipCode: 6028 },
    { city: "Lapu-Lapu City", zipCode: 6015 },
    { city: "Liloan", zipCode: 6002 },
    { city: "Mactan Airport", zipCode: 6016 },
    { city: "Madridejos", zipCode: 6053 },
    { city: "Malabuyoc", zipCode: 6029 },
    { city: "Mandaue City", zipCode: 6014 },
    { city: "Medellin", zipCode: 6012 },
    { city: "Minglanilla", zipCode: 6046 },
    { city: "Moalboal", zipCode: 6032 },
    { city: "Naga City", zipCode: 6037 },
    { city: "Oslob", zipCode: 6025 },
    { city: "Pilar", zipCode: 6048 },
    { city: "Pinamungahan", zipCode: 6039 },
    { city: "Poro", zipCode: 6049 },
    { city: "Ronda", zipCode: 6034 },
    { city: "Samboan", zipCode: 6027 },
    { city: "San Fernando", zipCode: 6018 },
    { city: "San Francisco", zipCode: 6050 },
    { city: "San Remigio", zipCode: 6011 },
    { city: "Santa Fe", zipCode: 6047 },
    { city: "Santander", zipCode: 6026 },
    { city: "Sibonga", zipCode: 6020 },
    { city: "Sogod", zipCode: 6007 },
    { city: "Tabogon", zipCode: 6009 },
    { city: "Tabuelan", zipCode: 6044 },
    { city: "Talisay City", zipCode: 6045 },
    { city: "Toledo City", zipCode: 6038 },
    { city: "Tuburan", zipCode: 6043 },
    { city: "Tudela", zipCode: 6051 },
    //Guimaras Sub-Province
    { city: "Buenavista", zipCode: 5044 },
    { city: "Jordan", zipCode: 5045 },
    { city: "Nueva Valencia", zipCode:  5046 },
    // Iloilo Province
    { city: "Ajuy", zipCode: 5012 },
    { city: "Alimodian", zipCode: 5028 },
    { city: "Anilao", zipCode: 5009 },
    { city: "Badiangan", zipCode: 5033 },
    { city: "Balasan", zipCode: 5018 },
    { city: "Banate", zipCode: 5010 },
    { city: "Barotac Nuevo", zipCode: 5007 },
    { city: "Barotac Viejo", zipCode: 5011 },
    { city: "Batad", zipCode: 5016 },
    { city: "Bingawan", zipCode: 5041 },
    { city: "Cabatuan", zipCode: 5031 },
    { city: "Calinog", zipCode: 5040 },
    { city: "Carles", zipCode: 5019 },
    { city: "Conception", zipCode: 5013 },
    { city: "Dingle", zipCode: 5035 },
    { city: "Dueñas", zipCode: 5038 },
    { city: "Dumangas", zipCode: 5006 },
    { city: "Estancia", zipCode: 5017 },
    { city: "Guimbal", zipCode: 5022 },
    { city: "Igbaras", zipCode: 5029 },
    { city: "Iloilo City", zipCode: 5000 },
    { city: "Janiuay", zipCode: 5034 },
    { city: "Lambunao", zipCode: 5042 },
    { city: "Leganes", zipCode: 5003 },
    { city: "Lemery", zipCode: 5043 },
    { city: "Leon", zipCode: 5026 },
    { city: "Maasin", zipCode: 5030 },
    { city: "Miagao", zipCode: 5023 },
    { city: "Mina", zipCode: 5032 },
    { city: "New Lucena", zipCode: 5005 },
    { city: "Oton", zipCode: 5020 },
    { city: "Passi", zipCode: 5037 },
    { city: "Pavia", zipCode: 5001 },
    { city: "Pototan", zipCode: 5008 },
    { city: "San Dionisio", zipCode: 5015 },
    { city: "San Enrique", zipCode: 5036 },
    { city: "San Joaquin", zipCode: 5024 },
    { city: "San Miguel", zipCode: 5025 },
    { city: "San Rafael", zipCode: 5039 },
    { city: "Santa Barbara", zipCode: 5002 },
    { city: "Sara", zipCode: 5014 },
    { city: "Tigbauan", zipCode: 5021 },
    { city: "Tubungan", zipCode: 5027 },
    { city: "Zarraga", zipCode: 5004 },
    // Leyte Province
    { city: "Abuyog", zipCode: 6510 },
    { city: "Alangalang", zipCode: 6517 },
    { city: "Albuera", zipCode: 6542 },
    { city: "Babatngon", zipCode: 6520 },
    { city: "Barugo", zipCode: 6519 },
    { city: "Bato", zipCode: 6525 },
    { city: "Baybay", zipCode: 6521 },
    { city: "Burauen", zipCode: 6516 },
    { city: "Calubian", zipCode: 6534 },
    { city: "Capoocan", zipCode: 6530 },
    { city: "Carigara", zipCode: 6529 },
    { city: "Dagami", zipCode: 6515 },
    { city: "Dulag", zipCode: 6505 },
    { city: "Hilongos", zipCode: 6524 },
    { city: "Hindang", zipCode: 6523 },
    { city: "Inopacan", zipCode: 6522 },
    { city: "Isabel", zipCode: 6539 },
    { city: "Jaro", zipCode: 6527 },
    { city: "Javier", zipCode: 6511 },
    { city: "Julita", zipCode: 6506 },
    { city: "Kananga", zipCode: 6531 },
    { city: "La Paz", zipCode: 6508 },
    { city: "Leyte", zipCode: 6533 },
    { city: "Macarthur", zipCode: 6509 },
    { city: "Mahaplag", zipCode: 6512 },
    { city: "Matag-Ob", zipCode: 6532 },
    { city: "Matalom", zipCode: 6526 },
    { city: "Mayorga", zipCode: 6507 },
    { city: "Merida", zipCode: 6540 },
    { city: "Ormoc City", zipCode: 6541 },
    { city: "Palo", zipCode: 6501 },
    { city: "Palompon", zipCode: 6538 },
    { city: "Pastrana", zipCode: 6514 },
    { city: "San Isidro", zipCode: 6535 },
    { city: "San Miguel", zipCode: 6518 },
    { city: "Santa Fe", zipCode: 6513 },
    { city: "Tabango", zipCode: 6536 },
    { city: "Tabontabon", zipCode: 6504 },
    { city: "Tacloban City", zipCode: 6500 },
    { city: "Tanauan", zipCode: 6502 },
    { city: "Tolosa", zipCode: 6503 },
    { city: "Tunga", zipCode: 6528 },
    { city: "Villaba", zipCode: 6537 },
    // Southern Leyte Province
    { city: "Anahawan", zipCode: 6610 },
    { city: "Bontoc", zipCode: 6604 },
    { city: "Hinunangan", zipCode: 6608 },
    { city: "Hinundayan", zipCode: 6609 },
    { city: "Libagon", zipCode: 6615 },
    { city: "Liloan", zipCode: 6612 },
    { city: "Maasin", zipCode: 6600 },
    { city: "Macrohon", zipCode: 6601 },
    { city: "Malitbog", zipCode: 6603 },
    { city: "Padre Burgos", zipCode: 6602 },
    { city: "Pintuyan", zipCode: 6614 },
    { city: "San Francisco", zipCode: 6613 },
    { city: "San Juan (Cabalian)", zipCode: 6611 },
    { city: "San Ricardo", zipCode: 6617 },
    { city: "Silago", zipCode: 6607 },
    { city: "Sogod", zipCode: 6606 },
    { city: "St. Bernard", zipCode: 6616 },
    { city: "Tomas Oppus", zipCode: 6605 },
    // Masbate Province
    { city: "Aroroy", zipCode:  5414 },
    { city: "Baleno", zipCode:  5413 },
    { city: "Balud", zipCode:  5412 },
    { city: "Batuan", zipCode:  5415 },
    { city: "Buenavista", zipCode:  5421 },
    { city: "Cataingan", zipCode:  5405 },
    { city: "Cawayan", zipCode:  5405 },
    { city: "Claveria", zipCode:  5419 },
    { city: "Dimasalang", zipCode:  5403 },
    { city: "Esperanza", zipCode:  5407 },
    { city: "Mandaon", zipCode:  5411 },
    { city: "Masbate", zipCode:  5400 },
    { city: "Milagros", zipCode:  5410 },
    { city: "Mobo", zipCode:  5401 },
    { city: "Montreal", zipCode:  5418 },
    { city: "Palanas", zipCode:  5404 },
    { city: "Pio V. Cruz", zipCode:  5406 },
    { city: "Placer", zipCode:  5408 },
    { city: "San Fernando", zipCode:  5416 },
    { city: "San Jacinto", zipCode:  5417 },
    { city: "San Pascual", zipCode:  5420 },
    { city: "Uson", zipCode:  5402 },
    // Misamis Occidental
    { city: "Aloran", zipCode: 7206 },
    { city: "Baliangao", zipCode: 7211 },
    { city: "Bonifacio", zipCode: 7215 },
    { city: "Calamba", zipCode: 7210 },
    { city: "Clarin", zipCode: 7201 },
    { city: "Concepcion", zipCode: 7213 },
    { city: "Jimenez", zipCode: 7204 },
    { city: "Lopez Jaena", zipCode: 7208 },
    { city: "Oroquieta City", zipCode: 7207 },
    { city: "Ozamis City", zipCode: 7200 },
    { city: "Panaon", zipCode: 7205 },
    { city: "Plaridel", zipCode: 7209 },
    { city: "Sapang Dalaga", zipCode: 7212 },
    { city: "Sinacaban", zipCode: 7203 },
    { city: "Tangub City", zipCode: 7214 },
    { city: "Tudela", zipCode: 7202 },
    // Misamis Oriental
    { city: "Alubijid", zipCode: 9018 },
    { city: "Balingasag", zipCode: 9005 },
    { city: "Balinguan", zipCode: 9011 },
    { city: "Binuangan", zipCode: 9008 },
    { city: "Cagayan de Oro City", zipCode: 9000 },
    { city: "Claveria", zipCode: 9004 },
    { city: "El Salvador", zipCode: 9017 },
    { city: "Gingoog City", zipCode: 9014 },
    { city: "Gitaum", zipCode: 9020 },
    { city: "Initao", zipCode: 9022 },
    { city: "Jasaan", zipCode: 9003 },
    { city: "Kinogitan", zipCode: 9010 },
    { city: "Lagonglong", zipCode: 9006 },
    { city: "Laguidingan", zipCode: 9019 },
    { city: "Libertad", zipCode: 9021 },
    { city: "Lugait", zipCode: 9025 },
    { city: "Magsaysay", zipCode: 9015 },
    { city: "Manticao", zipCode: 9024 },
    { city: "Medina", zipCode: 9013 },
    { city: "Naawan", zipCode: 9023 },
    { city: "Opol", zipCode: 9016 },
    { city: "Salay", zipCode: 9007 },
    { city: "Sugbongcogon", zipCode: 9009 },
    { city: "Tagoloan", zipCode: 9001 },
    { city: "Talisayan", zipCode: 9012 },
    { city: "Villanueva", zipCode: 9002 },
    // Negros Occidental
    { city: "Bacolod City", zipCode: 6100 },
    { city: "Bago City", zipCode: 6101 },
    { city: "Binalbagan", zipCode: 6107 },
    { city: "Cadiz City", zipCode: 6121 },
    { city: "Calatrava", zipCode: 6126 },
    { city: "Candoni", zipCode: 6110 },
    { city: "Enrique Magalona", zipCode: 6118 },
    { city: "Escalante", zipCode: 6124 },
    { city: "Himamaylan", zipCode: 6108 },
    { city: "Hinigaran", zipCode: 6106 },
    { city: "Hinoba-an", zipCode: 6114 },
    { city: "Ilog", zipCode: 6109 },
    { city: "Isabela", zipCode: 6128 },
    { city: "Kabankalan", zipCode: 6100 },
    { city: "Kauayan", zipCode: 6112 },
    { city: "La Carlota City", zipCode: 6130 },
    { city: "La Castellana", zipCode: 6131 },
    { city: "Manapla", zipCode: 6120 },
    { city: "Moises Padilla", zipCode: 6132 },
    { city: "Murcia", zipCode: 6129 },
    { city: "Paraiso (Fabrica)", zipCode: 6123 },
    { city: "Pulupandan", zipCode: 6102 },
    { city: "Pontevedra", zipCode: 6105 },
    { city: "Sagay", zipCode: 6122 },
    { city: "San Carlos City", zipCode: 6127 },
    { city: "San Enrique", zipCode: 6104 },
    { city: "Silay City", zipCode: 6116 },
    { city: "Silay Hawaiian Central", zipCode: 6117 },
    { city: "Sipalay", zipCode: 6113 },
    { city: "Talisay", zipCode: 6115 },
    { city: "Toboso", zipCode: 6125 },
    { city: "Valladolid", zipCode: 6103 },
    { city: "Victorias", zipCode: 6119 },
    // Negros Oriental
    { city: "Amian", zipCode: 6203 },
    { city: "Ayungon", zipCode: 6210 },
    { city: "Bacong", zipCode: 6216 },
    { city: "Bais City", zipCode: 6206 },
    { city: "Basay", zipCode: 6222 },
    { city: "Bayawan", zipCode: 6221 },
    { city: "Bindoy", zipCode: 6209 },
    { city: "Canlaon City", zipCode: 6223 },
    { city: "Dauin", zipCode: 6217 },
    { city: "Dumaguete City", zipCode: 6200 },
    { city: "Guihulngan", zipCode: 6214 },
    { city: "Jimalalud", zipCode: 6212 },
    { city: "La Libertad", zipCode: 6213 },
    { city: "Mabinay", zipCode: 6208 },
    { city: "Manjuyod", zipCode: 6208 },
    { city: "Pamplona", zipCode: 6205 },
    { city: "San Jose", zipCode: 6202 },
    { city: "Siaton", zipCode: 6219 },
    { city: "Sibulan", zipCode: 6201 },
    { city: "Sta. Catalina", zipCode: 6220 },
    { city: "Tanjay", zipCode: 6204 },
    { city: "Tayasan", zipCode: 6211 },
    { city: "Valencia", zipCode: 6215 },
    { city: "Valle Hermoso", zipCode: 6224 },
    { city: "Zamboanguita", zipCode: 6218 },
    // Romblon
    { city: "Alcantara", zipCode:  5509 },
    { city: "Banton (Jones)", zipCode:  5515 },
    { city: "Cajidiocan", zipCode:  5512 },
    { city: "Calatrava", zipCode:  5503 },
    { city: "Concepcion", zipCode:  5516 },
    { city: "Corcuera", zipCode:  5514 },
    { city: "Ferrol", zipCode:  5506 },
    { city: "Imelda", zipCode:  5502 },
    { city: "Looc", zipCode:  5507 },
    { city: "Magdiwang", zipCode:  5511 },
    { city: "Odiongan", zipCode:  5505 },
    { city: "Romblon", zipCode:  5500 },
    { city: "San Agustin", zipCode:  5501 },
    { city: "San Andres", zipCode:  5504 },
    { city: "San Fernando", zipCode:  5513 },
    { city: "San Jose", zipCode:  5510 },
    { city: "Santa Fe", zipCode:  5508 },
    // Eastern Samar
    { city: "Arteche", zipCode: 6822 },
    { city: "Balangiga", zipCode: 6812 },
    { city: "Balangkayan", zipCode: 6801 },
    { city: "Borongan", zipCode: 6800 },
    { city: "Can-Avid", zipCode: 6806 },
    { city: "Dolores", zipCode: 6817 },
    { city: "Gen. McArthur", zipCode: 6805 },
    { city: "Giporlos", zipCode: 6811 },
    { city: "Guiuan", zipCode: 6809 },
    { city: "Hernani", zipCode: 6804 },
    { city: "Jipapad", zipCode: 6819 },
    { city: "Lawa-an", zipCode: 6813 },
    { city: "Llorente", zipCode: 6803 },
    { city: "Maslog", zipCode: 6820 },
    { city: "Maydulog", zipCode: 6802 },
    { city: "Mercedes", zipCode: 6808 },
    { city: "Oras", zipCode: 6818 },
    { city: "Quinapundan", zipCode: 6810 },
    { city: "Salcedo", zipCode: 6807 },
    { city: "San Julian", zipCode: 6814 },
    { city: "San Policarpio", zipCode: 6821 },
    { city: "Sulat", zipCode: 6815 },
    { city: "Taft", zipCode: 6816 },
    // Northern Samar
    { city: "Allen", zipCode: 6405 },
    { city: "Biri", zipCode: 6410 },
    { city: "Bobon", zipCode: 6401 },
    { city: "Capul", zipCode: 6408 },
    { city: "Catarman", zipCode: 6400 },
    { city: "Catubig", zipCode: 6418 },
    { city: "Gamay", zipCode: 6422 },
    { city: "La Navas", zipCode: 6420 },
    { city: "Laoang", zipCode: 6411 },
    { city: "Lapineg", zipCode: 6423 },
    { city: "Lavezares", zipCode: 6404 },
    { city: "Lope de Vega", zipCode: 6403 },
    { city: "Mapanas", zipCode: 6412 },
    { city: "Mondragon", zipCode: 6417 },
    { city: "Palapag", zipCode: 6421 },
    { city: "Pambujan", zipCode: 6413 },
    { city: "Rosario", zipCode: 6416 },
    { city: "San Antonio", zipCode: 6407 },
    { city: "San Isidro", zipCode: 6409 },
    { city: "San Jose", zipCode: 6402 },
    { city: "San Roque", zipCode: 6415 },
    { city: "San Vicente", zipCode: 6419 },
    { city: "Silvino Lubos", zipCode: 6414 },
    { city: "Victoria", zipCode: 6406 },
    // Western Samar
    { city: "Almagro", zipCode: 6724 },
    { city: "Basey", zipCode: 6720 },
    { city: "Calbayog City", zipCode: 6710 },
    { city: "Calbiga", zipCode: 6715 },
    { city: "Catbalogan", zipCode: 6700 },
    { city: "Daram", zipCode: 6722 },
    { city: "Gandara", zipCode: 6706 },
    { city: "Hinbangan", zipCode: 6713 },
    { city: "Jiabong", zipCode: 6701 },
    { city: "Marabut", zipCode: 6721 },
    { city: "Matuguinao", zipCode: 6708 },
    { city: "Motiong", zipCode: 6702 },
    { city: "Pagsanjan", zipCode: 6705 },
    { city: "Pinabacdao", zipCode: 6716 },
    { city: "San Jorge", zipCode: 6707 },
    { city: "San Jose de Bauan", zipCode: 6723 },
    { city: "San Sebastian", zipCode: 6714 },
    { city: "Sta. Margarita", zipCode: 6709 },
    { city: "Sta. Rita", zipCode: 6718 },
    { city: "Sto. Nino", zipCode: 6711 },
    { city: "Tagapulan", zipCode: 6712 },
    { city: "Talarora", zipCode: 6719 },
    { city: "Tarangnan", zipCode: 6704 },
    { city: "Villareal", zipCode: 6717 },
    { city: "Wright", zipCode: 6703 },
    { city: "Zumarraga", zipCode: 6725 },
    // Siquijor Province
    { city: "Enrile Villanueva", zipCode: 6230 },
    { city: "Larena", zipCode: 6226 },
    { city: "Lazi", zipCode: 6228 },
    { city: "Maria", zipCode: 6229 },
    { city: "San Juan", zipCode: 6227 },
    { city: "Siquijor", zipCode: 6225 }
]

export const Mindanao = [
    //Mindanao
    //Agusan del Norte
    { city: "Buenavista", zipCode: 8601 },
    { city: "Butuan City", zipCode: 8600 },
    { city: "Cabadbaran", zipCode: 8605 },
    { city: "Carmen", zipCode: 8603 },
    { city: "Jabonga", zipCode: 8607 },
    { city: "Kitcharao", zipCode: 8609 },
    { city: "La Nieves", zipCode: 8610 },
    { city: "Magallanes", zipCode: 8604 },
    { city: "Nasipit", zipCode: 8602 },
    { city: "Remedios T. Romualdez", zipCode: 8611 },
    { city: "Santiago", zipCode: 8608 },
    { city: "Tubay", zipCode: 8606 },
    //Agusan del Sur
    { city: "Bayugan", zipCode: 8502 },
    { city: "Bunawan", zipCode: 8506 },
    { city: "Esperanza", zipCode: 8513 },
    { city: "La Paz", zipCode: 8508 },
    { city: "Loreto", zipCode: 8507 },
    { city: "Prosperidad", zipCode: 8500 },
    { city: "Rosario", zipCode: 8504 },
    { city: "San Francisco", zipCode: 8501 },
    { city: "San Luis", zipCode: 8511 },
    { city: "Santa Josefa", zipCode: 8512 },
    { city: "Sibagat", zipCode: 8503 },
    { city: "Talacogon", zipCode: 8510 },
    { city: "Trento", zipCode: 8505 },
    { city: "Veruela", zipCode: 8509 },
    //Basilan
    { city: "Isabela de Basilan", zipCode: 7300 },
    { city: "Lamitan", zipCode: 7302 },
    { city: "Lantawan", zipCode: 7301 },
    { city: "Maluso", zipCode: 7303 },
    { city: "Sumisip", zipCode: 7305 },
    { city: "Tipo-Tipo", zipCode: 7304 },
    { city: "Tuburan", zipCode: 7306 },
    //Bukidnon
    { city: "Baungon", zipCode: 8707 },
    { city: "Damulog", zipCode: 8721 },
    { city: "Dangcagan", zipCode: 8719 },
    { city: "Don Carlos", zipCode: 8712 },
    { city: "Impasugong", zipCode: 8702 },
    { city: "Kabanglasan", zipCode: 8723 },
    { city: "Kadingilan", zipCode: 8713 },
    { city: "Kalilangan", zipCode: 8718 },
    { city: "Kibawe", zipCode: 8720 },
    { city: "Kitaotao", zipCode: 8716 },
    { city: "Lantapan", zipCode: 8722 },
    { city: "Libuna", zipCode: 8706 },
    { city: "Malaybalay", zipCode: 8700 },
    { city: "Malitbog", zipCode: 8704 },
    { city: "Manolo Fortich", zipCode: 8703 },
    { city: "Maramag", zipCode: 8714 },
    { city: "Pangantucan", zipCode: 8717 },
    { city: "Philips", zipCode: 8705 },
    { city: "Quezon", zipCode: 8715 },
    { city: "San Fernando", zipCode: 8711 },
    { city: "Sumilao", zipCode: 8701 },
    { city: "Talakag", zipCode: 8708 },
    { city: "Valencia", zipCode: 8709 },
    //Camiguin
    { city: "Catarman", zipCode: 9104 },
    { city: "Guinsiliban", zipCode: 9102 },
    { city: "Mahinog", zipCode: 9101 },
    { city: "Mambajao", zipCode: 9100 },
    { city: "Sagay", zipCode: 9103 },
    //Compostela Valley
    { city: "Compostela", zipCode: 8803 },
    { city: "Laak", zipCode: 8810 },
    { city: "Mabini", zipCode: 8807 },
    { city: "Maco", zipCode: 8806 },
    { city: "Maragusan", zipCode: 8808 },
    { city: "Mawab", zipCode: 8802 },
    { city: "Monkayo", zipCode: 8805 },
    { city: "Montevista", zipCode: 8801 },
    { city: "Nabunturan", zipCode: 8800 },
    { city: "New Bataan", zipCode: 8804 },
    { city: "Pantukan", zipCode: 8809 },
    //North Cotabato
    { city: "Alamada", zipCode: 9413 },
    { city: "Aleosan", zipCode: 9415 },
    { city: "Antipas", zipCode: 9414 },
    { city: "Arakan", zipCode: 9417 },
    { city: "Banisilan", zipCode: 9416 },
    { city: "Carmen", zipCode: 9408 },
    { city: "Kabacan", zipCode: 9407 },
    { city: "Kidapawan", zipCode: 9400 },
    { city: "Libungan", zipCode: 9411 },
    { city: "Magpet", zipCode: 9404 },
    { city: "Makilala", zipCode: 9401 },
    { city: "Matalam", zipCode: 9406 },
    { city: "Midsayap", zipCode: 9410 },
    { city: "M'lang", zipCode: 9402 },
    { city: "Pigkawayan", zipCode: 9412 },
    { city: "Pikit", zipCode: 9409 },
    { city: "Pres. Roxas", zipCode: 9405 },
    { city: "Tulunan", zipCode: 9403 },
    //South Cotabato
    { city: "Banga", zipCode: 9511 },
    { city: "General Santos City", zipCode: 9500 },
    { city: "Koronadal", zipCode: 9506 },
    { city: "Norala", zipCode: 9508 },
    { city: "Polomolok", zipCode: 9504 },
    { city: "Santo Niño", zipCode: 9509 },
    { city: "Surallah", zipCode: 9512 },
    { city: "Tampacan", zipCode: 9507 },
    { city: "Tantangan", zipCode: 9510 },
    { city: "T'boli", zipCode: 9513 },
    { city: "Tupi", zipCode: 9505 },
    //Davao del Norte
    { city: "Asuncion", zipCode: 8102 },
    { city: "Babak", zipCode: 8118 },
    { city: "Carmen", zipCode: 8101 },
    { city: "Kapalong", zipCode: 8113 },
    { city: "Kaputian", zipCode: 8120 },
    { city: "New Corella", zipCode: 8104 },
    { city: "Panabo", zipCode: 8105 },
    { city: "Samal", zipCode: 8119 },
    { city: "San Mariano", zipCode: 8116 },
    { city: "San Vicente", zipCode: 8103 },
    { city: "Santo Tomas", zipCode: 8112 },
    { city: "Tagum", zipCode: 8100 },
    //Davao del Sur
    { city: "Bansalan", zipCode: 8005 },
    { city: "Davao City", zipCode: 8000 },
    { city: "Digos", zipCode: 8002 },
    { city: "Don Marcelino", zipCode: 8013 },
    { city: "Hagunoy", zipCode: 8006 },
    { city: "Jose Abad Santos", zipCode: 8014 },
    { city: "Kiblawan", zipCode: 8008 },
    { city: "Magsaysay", zipCode: 8004 },
    { city: "Malalag", zipCode: 8010 },
    { city: "Malita", zipCode: 8012 },
    { city: "Matanao", zipCode: 8003 },
    { city: "Padada", zipCode: 8007 },
    { city: "Santa Cruz", zipCode: 8001 },
    { city: "Santa Maria", zipCode: 8011 },
    { city: "Sarangani", zipCode: 8015 },
    //Davao Oriental
    { city: "Baganga", zipCode: 8204 },
    { city: "Banaybanay", zipCode: 8208 },
    { city: "Boston", zipCode: 8206 },
    { city: "Caraga", zipCode: 8203 },
    { city: "Cateel", zipCode: 8205 },
    { city: "Gov. Generoso", zipCode: 8210 },
    { city: "Lopon", zipCode: 8207 },
    { city: "Manay", zipCode: 8202 },
    { city: "Mati", zipCode: 8200 },
    { city: "San Isidro", zipCode: 8209 },
    { city: "Tarragona", zipCode: 8201 },
    //Lanao del Norte 
    { city: "Bacolod", zipCode: 9205 },
    { city: "Baloi", zipCode: 9217 },
    { city: "Baroy", zipCode: 9210 },
    { city: "Iligan City", zipCode: 9200 },
    { city: "Kapatagan", zipCode: 9214 },
    { city: "Karomatan", zipCode: 9215 },
    { city: "Kauswagan", zipCode: 9202 },
    { city: "Kolambugan", zipCode: 9207 },
    { city: "Lala", zipCode: 9211 },
    { city: "Linamon", zipCode: 9201 },
    { city: "Magsaysay", zipCode: 9221 },
    { city: "Maigo", zipCode: 9206 },
    { city: "Matugao", zipCode: 9203 },
    { city: "Munai", zipCode: 9219  },
    { city: "Nunungan", zipCode: 9216 },
    { city: "Pantao Ragat", zipCode: 9208},
    { city: "Pantar", zipCode: 9218},
    { city: "Poona Piagapo", zipCode: 9204},
    { city: "Salvador", zipCode: 9212 },
    { city: "Sapad", zipCode: 9213 },
    { city: "Tagoloan", zipCode: 9222 },
    { city: "Tangkal", zipCode: 9220 },
    { city: "Tubod", zipCode: 9209},
    // Lanao Del Sur
    { city: "Bacolod Grande", zipCode: 9316  },
    { city: "Blabagan", zipCode: 9302 },
    { city: "Balindong", zipCode: 9318 },
    { city: "Bayang", zipCode: 9309},
    { city: "Binidayan", zipCode: 9310 },
    { city: "Baumbaran", zipCode: 9320 },
    { city: "Butig", zipCode: 9305},
    { city: "Calanogas", zipCode: 9319},
    { city: "Ganassi", zipCode: 9311 },
    { city: "Lumbatan", zipCode: 9307},
    { city: "Lumbayanague", zipCode: 9306 },
    { city: "Macador Andong", zipCode: 9308 },
    { city: "Madalum", zipCode: 9315},
    { city: "Madamba", zipCode: 9314 },
    { city: "Malabang", zipCode: 9300 },
    { city: "Maragong", zipCode: 9303 },
    { city: "Pagayawan", zipCode: 9312 },
    { city: "Pualas", zipCode: 9313 },
    { city: "Sultan Gumander", zipCode: 9303 },
    { city: "Tagoloan II", zipCode: 9321 },
    { city: "Tubaran", zipCode: 9304},
    { city: "Tugaya", zipCode: 9317},
    { city: "Buadiposo Buntong", zipCode: 9714 },
    { city: "Bubong", zipCode: 9708},
    { city: "Kapal", zipCode: 9709 },
    { city: "Lumba Bayabao", zipCode: 9703 },
    { city: "Maguing", zipCode: 9715 },
    { city: "Marangtao", zipCode: 9711 },
    { city: "Marawi City", zipCode: 9700 },
    { city: "Masio", zipCode: 9706},
    { city: "Mulondo", zipCode: 9702 },
    { city: "Piagapo", zipCode: 9710 },
    { city: "Poona Bayabao", zipCode: 9705 },
    { city: "Ramain-Ditsaan", zipCode: 9713 },
    { city: "Saguiaran", zipCode: 9701 },
    { city: "Tamparan", zipCode: 9704 },
    { city: "Taraka", zipCode: 9712},
    { city: "Wao", zipCode: 9716 },
    // Maguindanao
    { city: "Ampatuan", zipCode: 9609  },
    { city: "Barira", zipCode: 9614 },
    { city: "Buldon", zipCode: 9615 },
    { city: "Buluan", zipCode: 9616},
    { city: "Cotabato City", zipCode: 9600 },
    { city: "Datu Paglas", zipCode: 9617},
    { city: "Datu Piang", zipCode: 9607},
    { city: "Datu Odin Sinsuat(Dinaig)", zipCode: 9601},
    { city: "Gen. S. K. Datun", zipCode: 9618 },
    { city: "Kabuntulan", zipCode: 9606},
    { city: "Maganoy", zipCode: 9608 },
    { city: "Matanog", zipCode: 9613 },
    { city: "Pagalungan", zipCode: 9610},
    { city: "Parang", zipCode: 9604 },
    { city: "South Upi", zipCode: 9603},
    { city: "Sultan Kudarat", zipCode: 9605 },
    { city: "Sultan Sa Barongis", zipCode: 9611 },
    { city: "Talayan", zipCode: 9612},
    { city: "Upi", zipCode: 9602},
    // Sarangani
    { city: "Alabel", zipCode: 9501 },
    { city: "Glan", zipCode: 9517 },
    { city: "Kiamba", zipCode: 9514 },
    { city: "Maasim", zipCode: 9502 },
    { city: "Maitum", zipCode: 9515 },
    { city: "Malapatan", zipCode: 9516 },
    { city: "Malungon", zipCode: 9503 },
    // Sultan Kudarat
    { city: "Bagumbayan", zipCode: 9810 },
    { city: "Colombio", zipCode: 9801 },
    { city: "Esperanza(Ampatuan)", zipCode: 9806 },
    { city: "Isulan", zipCode: 9805},
    { city: "Kalamansig", zipCode: 9808 },
    { city: "Lebak(Salaman)", zipCode: 9807 },
    { city: "Lutayan", zipCode: 9803},
    { city: "Mariano Marcos", zipCode: 9802 },
    { city: "Palimbang", zipCode: 9809},
    { city: "Pres. Quirino", zipCode: 9804 },
    { city: "Sen Ninoy Aquino", zipCode: 9811 },
    { city: "Takurong", zipCode: 9800},
    // Sulu Province
    { city: "Indanan", zipCode: 7407 },
    { city: "Jolo", zipCode: 7400 },
    { city: "Kalingalan Kalauang", zipCode: 7416 },
    { city: "Lugus", zipCode: 7411},
    { city: "Luuk", zipCode: 7404 },
    { city: "Maimbung", zipCode: 7409 },
    { city: "Marungas", zipCode: 7413},
    { city: "Panamao", zipCode: 7402},
    { city: "Panglima Estino", zipCode: 7415},
    { city: "Panguntaran", zipCode: 7414},
    { city: "Parang", zipCode: 7408 },
    { city: "Pata", zipCode: 7405},
    { city: "Patikul", zipCode: 7401},
    { city: "Siasi", zipCode: 7412 },
    { city: "Talipao", zipCode: 7403},
    { city: "Tapul", zipCode: 7410 },
    { city: "Tongkil", zipCode: 7406 },
    // Surigao del Norte
    { city: "Alegria", zipCode: 8425 },
    { city: "Bacuag", zipCode: 8408 },
    { city: "Basilisa(Rizal)", zipCode: 8413 },
    { city: "Burgos", zipCode: 8424},
    { city: "Cagdianao", zipCode: 8411 },
    { city: "Claver", zipCode: 8410 },
    { city: "Dapa", zipCode: 8417},
    { city: "Del Carmen", zipCode: 8418},
    { city: "Dinagat", zipCode: 8412},
    { city: "Gen. Luna", zipCode: 8419},
    { city: "Gigaquit", zipCode: 8409 },
    { city: "Libjo(Albor)", zipCode: 8414},
    { city: "Loreto", zipCode: 8415},
    { city: "Mainit", zipCode: 8407 },
    { city: "Malimano", zipCode: 8402},
    { city: "Pilar", zipCode: 8420 },
    { city: "Placer", zipCode: 8405 },
    { city: "San Benito", zipCode: 8423},
    { city: "San Francisco", zipCode: 8401},
    { city: "San Isidro", zipCode: 8421},
    { city: "San Jose", zipCode: 8427},
    { city: "Santa Monica", zipCode: 8422},
    { city: "Sison", zipCode: 8404 },
    { city: "Socorro", zipCode: 8416},
    { city: "Surigao City", zipCode: 8400},
    { city: "Tagana-an", zipCode: 8403},
    { city: "Tubajon", zipCode: 8426},
    { city: "Tubod", zipCode: 8406},
    // Surigao del Sur
    { city: "Barobo", zipCode: 8309 },
    { city: "Bayabas", zipCode: 8303 },
    { city: "Bislig", zipCode: 8311 },
    { city: "Cagwait", zipCode: 8311},
    { city: "Cantillan", zipCode: 8317 },
    { city: "Carmen", zipCode: 8315 },
    { city: "Carrascal", zipCode: 8318 },
    { city: "Cortez", zipCode: 8313 },
    { city: "Hinatuan", zipCode: 8310 },
    { city: "Lanuza", zipCode: 8314 },
    { city: "Lianga", zipCode: 8307 },
    { city: "Lingig", zipCode: 8312},
    { city: "Madrid", zipCode: 8316},
    { city: "Marihatag", zipCode: 8306 },
    { city: "San Agustin", zipCode: 8305},
    { city: "San Miguel", zipCode: 8301 },
    { city: "Tagbina", zipCode: 8308 },
    { city: "Tago", zipCode: 8302},
    { city: "Tandag", zipCode: 8300},
    // Tawi-tawi
    { city: "Balimbing", zipCode: 7501 },
    { city: "Bongao", zipCode: 7500 },
    { city: "Cagayan de Sulu", zipCode: 7508 },
    { city: "Languyan", zipCode: 7509 },
    { city: "Sapa-sapa", zipCode: 7503 },
    { city: "Simunol", zipCode: 7505 },
    { city: "Sitangkai", zipCode: 7506 },
    { city: "South Ubian", zipCode: 7504 },
    { city: "Taganak(Turtle Island)", zipCode: 7507},
    { city: "Tandu Bas", zipCode: 7502 },
    // Zamboangga del Norte
    { city: "Baliguian", zipCode: 7123 },
    { city: "Dapitan City", zipCode: 7101 },
    { city: "Dipolog City", zipCode: 7100 },
    { city: "Gutalac", zipCode: 7108},
    { city: "Jose Dalman(Ponot)", zipCode: 7111 },
    { city: "Kalawit", zipCode: 7124 },
    { city: "Katipunan", zipCode: 7109 },
    { city: "Labason", zipCode: 7117 },
    { city: "La Libertad", zipCode: 7119},
    { city: "Liloy", zipCode: 7115},
    { city: "Manukan", zipCode: 7110 },
    { city: "Mutia", zipCode: 7107},
    { city: "Pinan", zipCode: 7105},
    { city: "Polanco", zipCode: 7106 },
    { city: "Rizal", zipCode:  7104},
    { city: "Roxas", zipCode: 7102  },
    { city: "Salug", zipCode: 7114 },
    { city: "Sergio Osmena", zipCode: 7108 },
    { city: "Siayan", zipCode: 7113 },
    { city: "Sibuco", zipCode: 7122},
    { city: "Sibutad", zipCode: 7103 },
    { city: "Sindangan(Leon B. Postigo)", zipCode: 7112 },
    { city: "Siocon", zipCode: 7120 },
    { city: "Siraway", zipCode: 7121},
    { city: "Tampilisan", zipCode: 7116},
    // Zamboanga del Sur
    { city: "Alicia", zipCode: 7040 },
    { city: "Aurora", zipCode: 7020},
    { city: "Bayog", zipCode: 7011 },
    { city: "Buug", zipCode: 7009 },
    { city: "Dimataling", zipCode: 7032 },
    { city: "Dinas", zipCode: 7030 },
    { city: "Diplahan", zipCode: 7039 },
    { city: "Don Mariano Marcos", zipCode: 7022},
    { city: "Dumalinao", zipCode: 7015 },
    { city: "Dumingag", zipCode: 7028 },
    { city: "Guipos", zipCode: 7042},
    { city: "Imelda", zipCode: 7007 },
    { city: "Ipil", zipCode: 7001},
    { city: "Josefina", zipCode: 7027},
    { city: "Kabalasan", zipCode: 7005 },
    { city: "Kumalarang", zipCode: 7013},
    { city: "Labangan", zipCode: 7017},
    { city: "Lakewood", zipCode:  7014},
    { city: "Lapuyan", zipCode: 7037},
    { city: "Mabuhay", zipCode: 7010 },
    { city: "Mahayag", zipCode: 7026 },
    { city: "Malangas", zipCode: 7038 },
    { city: "Margo Sa Tubig", zipCode: 7035 },
    { city: "Midsalip", zipCode: 7021},
    { city: "Molave", zipCode: 7023 },
    { city: "Naga", zipCode: 7004 },
    { city: "Oluntanga", zipCode: 7041},
    { city: "Pagadian City", zipCode: 7016},
    { city: "Payao", zipCode: 7008 },
    { city: "Pitogo", zipCode: 7033},
    { city: "Ramon Magsaysay", zipCode: 7024 },
    { city: "Reseller Lim", zipCode: 7002 },
    { city: "San Miguel", zipCode: 7029 },
    { city: "San Pablo", zipCode: 7031 },
    { city: "Siay", zipCode: 7006},
    { city: "Tabina", zipCode: 7034 },
    { city: "Talusan", zipCode: 7012 },
    { city: "Tambulig", zipCode: 7025},
    { city: "Tigbad", zipCode: 7043},
    { city: "Titay", zipCode: 7003 },
    { city: "Tukuran", zipCode: 7019 },
    { city: "Tungawan", zipCode: 7018 },
    { city: "Vicencio Sagun", zipCode: 7036 },
    { city: "Zamboanga City", zipCode: 7000}
]












